version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: dsp-db
    # restart: unless-stopped
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dsp_database
      MYSQL_USER: dsp_user
      MYSQL_PASSWORD: dsp_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql  # volume persistant
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro # init les bdd et table
      - ./docker/db/data.sql:/docker-entrypoint-initdb.d/02-data.sql:ro # init des data
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build: ./back-end #chemin du dossier o√π se trouve le Dockerfile
    container_name: dsp-backend
    env_file:
      - ./back-end/.env.production
    ports:
      - "8001:8001"
    # volumes:
    #   - ./back-end:/app
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./front-end
    container_name: dsp-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
