name: CI - Backend Jest (Mock DB)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      # 1. Cloner le dépôt
      - uses: actions/checkout@v4

      # 2. Installer Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.16.0'

      # 3. Installer toutes les dépendances backend (pour supertest il faut juste penser à push le package.json) 
      - name: Install backend dependencies
        run: |
          cd back-end
          npm install
          npm install --save helmet cors cookie-parser supertest

      # 4. Installer Babel pour Jest
      - name: Install Babel for Jest
        run: |
          cd back-end
          npm install --save-dev @babel/core @babel/preset-env babel-jest


     # 5. Lancer les tests Jest avec NODE_ENV=test et variables AES
      - name: Run Jest tests
        env:
          NODE_ENV: test
          AES_SECRET_KEY: 1234567890abcdef1234567890abcdef
          AES_IV: abcdef1234567890abcdef1234567890
        run: |
          cd back-end
          npx jest --runInBand --detectOpenHandles

      # 6. Upload logs si échec
      - name: Upload Jest logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: jest-logs
          path: back-end/test-results

